# oladimeji-kazeem/budgetpro/budgetpro-ab94e7d262d0d24f247fd60a27eb8be6e83a6e36/budget_input/migrations/0001_initial.py
# Generated by Django on 2025-10-17 
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0004_fundtransaction_managedfundhistorical_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100, unique=True, verbose_name='Budget Version Name')),
                ('mgmt_fee_rate', models.DecimalField(decimal_places=4, default=0.005, max_digits=5, verbose_name='Mgmt. Fee Rate (%)')),
                ('admin_fee_rate', models.DecimalField(decimal_places=4, default=0.001, max_digits=5, verbose_name='Admin Fee Rate (%)')),
                ('staff_cost_percent', models.DecimalField(decimal_places=4, default=0.25, max_digits=5, verbose_name='Staff Cost (% of Revenue)')),
                ('admin_expense_growth', models.DecimalField(decimal_places=4, default=0.05, max_digits=5, verbose_name='Admin Expense Growth (%)')),
                ('new_fund_aum_growth', models.DecimalField(decimal_places=4, default=0.1, max_digits=5, verbose_name='New Fund AUM Growth (%)')),
                ('investment_return_rate', models.DecimalField(decimal_places=4, default=0.08, max_digits=5, verbose_name='Investment Return Rate (%)')),
                ('target_current_ratio', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Target Current Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('period_start_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.datedetail', to_field='date', verbose_name='Period Start Date')),
            ],
            options={
                'verbose_name': 'Budget Assumption',
                'verbose_name_plural': 'Budget Assumptions',
                'ordering': ['-period_start_date', 'version_name'],
            },
        ),
    ]