# Generated by Django 5.2.7 on 2025-10-17 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_input", "0001_initial"),
        ("setup", "0005_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_year", models.PositiveSmallIntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("OPEX", "Operational Expenditure (OPEX)"),
                            ("CAPEX", "Capital Expenditure (CAPEX)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "annual_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=18,
                        verbose_name="Annual Budget Amount (₦)",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=18,
                        verbose_name="Monthly Equivalent (₦)",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Unit Cost (₦)",
                    ),
                ),
                ("justification", models.TextField(blank=True, null=True)),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending Approval", max_length=50)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.department",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.glaccount",
                        verbose_name="Expense GL Account",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="setup.location"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget Transaction",
                "verbose_name_plural": "Budget Transactions (OPEX/CAPEX)",
                "ordering": ["-budget_year", "department", "gl_account"],
            },
        ),
        migrations.CreateModel(
            name="PINDataSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_year", models.PositiveSmallIntegerField()),
                ("active_pins", models.IntegerField(default=0)),
                ("non_active_pins", models.IntegerField(default=0)),
                ("never_funded_pins", models.IntegerField(default=0)),
                ("new_enrolments", models.IntegerField(default=0)),
                (
                    "avg_contribution_existing",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Avg Contribution - Existing PINs (₦)",
                    ),
                ),
                (
                    "avg_contribution_new",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=18,
                        verbose_name="Avg Contribution - New PINs (₦)",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.department",
                    ),
                ),
                (
                    "fund_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.rsafund",
                        verbose_name="RSA Fund Type",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_pin_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PIN Data Submission",
                "verbose_name_plural": "PIN Data Submissions",
                "ordering": ["-budget_year", "department"],
                "unique_together": {("budget_year", "fund_type", "department")},
            },
        ),
    ]
