# Generated by Django 5.2.7 on 2025-10-17 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_input", "0002_budgettransaction_pindatasubmission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pindatasubmission",
            name="approval_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pindatasubmission",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_pin_data",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pindatasubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Executive Approval"),
                    ("REJECTED", "Rejected / Requires Rework"),
                    ("APPROVED", "Approved"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
