# Generated by Django 5.2.7 on 2025-10-17 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_input", "0003_pindatasubmission_approval_date_and_more"),
        ("setup", "0005_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovedBudgetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="Approved Scenario Name",
                    ),
                ),
                ("forecast_year", models.PositiveSmallIntegerField()),
                (
                    "final_net_profit",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "final_closing_cash",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Executive Approval"),
                            ("REJECTED", "Rejected / Requires Rework"),
                            ("APPROVED", "Approved"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "base_assumption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budget_input.budgetassumption",
                        verbose_name="Base Assumption Used",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_forecasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved Budget Version",
                "verbose_name_plural": "Approved Budget Versions",
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="ForecastGLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_month", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "approved_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget_input.approvedbudgetversion",
                    ),
                ),
                (
                    "gl_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.glaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast GL Transaction",
                "verbose_name_plural": "Forecast GL Transactions",
                "ordering": ["budget_month", "gl_account"],
                "unique_together": {("approved_version", "budget_month", "gl_account")},
            },
        ),
    ]
