# Generated by Django 5.2.7 on 2025-10-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GLAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gl_account_code",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="GL Account Code"
                    ),
                ),
                (
                    "gl_account_name",
                    models.CharField(max_length=200, verbose_name="GL Account Name"),
                ),
                ("category", models.CharField(max_length=50, verbose_name="Category")),
                (
                    "sub_category",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Sub-Category",
                    ),
                ),
                (
                    "financial_statement",
                    models.CharField(
                        choices=[
                            ("Income Statement", "Income Statement"),
                            ("Balance Sheet", "Balance Sheet"),
                            ("Cash Flow", "Cash Flow"),
                        ],
                        max_length=50,
                        verbose_name="Financial Statement",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(max_length=50, verbose_name="Account Type"),
                ),
                (
                    "is_postable",
                    models.BooleanField(default=True, verbose_name="Is Postable"),
                ),
                (
                    "normal_balance",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")],
                        max_length=10,
                        verbose_name="Normal Balance",
                    ),
                ),
                (
                    "active_flag",
                    models.BooleanField(default=True, verbose_name="Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_postable": False},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="setup.glaccount",
                        verbose_name="Parent Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Account",
                "verbose_name_plural": "GL Accounts",
                "ordering": ["gl_account_code"],
            },
        ),
    ]
