# Generated by Django 5.2.7 on 2025-10-12 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0002_glaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "journal_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("document_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reference_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entity_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cost_center_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("currency_code", models.CharField(default="NGN", max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=18),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                ("posted_flag", models.BooleanField(default=True)),
                ("posted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "source_module",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("reversal_flag", models.BooleanField(default=False)),
                ("reversal_ref_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "date_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.datedetail",
                        to_field="date",
                        verbose_name="Date Details Reference",
                    ),
                ),
                (
                    "gl_account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.glaccount",
                        to_field="gl_account_code",
                        verbose_name="GL Account Code",
                    ),
                ),
                (
                    "user_posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Transaction",
                "verbose_name_plural": "GL Transactions",
                "indexes": [
                    models.Index(
                        fields=["transaction_date", "gl_account_code"],
                        name="setup_gltra_transac_936ffb_idx",
                    )
                ],
            },
        ),
    ]
