# Generated by Django 5.2.7 on 2025-10-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0003_gltransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("entity_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "contributions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "withdrawals",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
                ),
                (
                    "balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        null=True,
                        verbose_name="RSA Fund Balance",
                    ),
                ),
                (
                    "investment_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        null=True,
                        verbose_name="Managed Fund Value",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("RSA", "RSA Fund"), ("MANAGED", "Managed Fund")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "managed_fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.managedfund",
                        verbose_name="Managed Fund",
                    ),
                ),
                (
                    "rsa_fund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup.rsafund",
                        verbose_name="RSA Fund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Transaction",
                "verbose_name_plural": "Fund Transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="ManagedFundHistorical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_end_date", models.DateField(db_index=True)),
                (
                    "aum_closing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "contribution",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "payout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "expected_asset_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "returns",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "managed_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="setup.managedfund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Managed Fund Historical",
                "verbose_name_plural": "Managed Fund Historicals",
                "ordering": ["period_end_date"],
                "unique_together": {("managed_fund", "period_end_date")},
            },
        ),
        migrations.CreateModel(
            name="RSAFundHistorical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_end_date", models.DateField(db_index=True)),
                (
                    "aum_closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="AUM/Balance",
                    ),
                ),
                (
                    "average_contribution_existing",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "average_contribution_new",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                ("total_pins", models.IntegerField(default=0)),
                ("active_pins", models.IntegerField(default=0)),
                ("never_funded_pins", models.IntegerField(default=0)),
                ("enrolments", models.IntegerField(default=0)),
                (
                    "rsa_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="setup.rsafund"
                    ),
                ),
            ],
            options={
                "verbose_name": "RSA Fund Historical",
                "verbose_name_plural": "RSA Fund Historicals",
                "ordering": ["period_end_date"],
                "unique_together": {("rsa_fund", "period_end_date")},
            },
        ),
    ]
