# Generated by Django 4.2.25 on 2025-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0005_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="datedetail",
            name="calendar_year",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="date_key",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="day",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="day_name",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="fiscal_year",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="is_weekend",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="month_name",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="month_short",
            field=models.CharField(blank=True, editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="month_year",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="quarter_year",
            field=models.CharField(
                blank=True, editable=False, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="week_of_year",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="year_month",
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name="datedetail",
            name="year_quarter",
            field=models.CharField(blank=True, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="half_year",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="month",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="quarter",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True
            ),
        ),
    ]
