# Generated by Django 4.2.25 on 2025-10-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("setup", "0006_datedetail_calendar_year_datedetail_date_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datedetail",
            name="quarter_year",
        ),
        migrations.AddField(
            model_name="datedetail",
            name="quarter_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=10,
                null=True,
                verbose_name="QtrName",
            ),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="day_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=10,
                null=True,
                verbose_name="DayName",
            ),
        ),
        migrations.AlterField(
            model_name="datedetail",
            name="month_name",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=10,
                null=True,
                verbose_name="MonthName",
            ),
        ),
    ]
